---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-seamless-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-seamless-app
  template:
    metadata:
      labels:
        app: k8s-seamless-app
    spec:
      containers:
        - name: app
          imagePullPolicy: IfNotPresent
          image: k8s-seamless:latest
          ports:
            - name: app-port
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/customized
              port: app-port
            failureThreshold: 30
            periodSeconds: 10
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: k8s-seamless-service
spec:
  type: NodePort
  selector:
    app: k8s-seamless-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
